### ISSUE TITLE
Enable docker push CI

### ISSUE THREAD

**Issue by williamdes** [hickory-dns/docker#1]
Hi @bluejekyll 

could you set up the CI for publishing docker images ?

- https://github.com/trust-dns/docker/settings/environments/new
    - Use "[docker-hub](https://github.com/trust-dns/docker/blob/master/.github/workflows/publish.yml#L9)" and save
- Go to the environment "docker-hub" page from the list on https://github.com/trust-dns/docker/settings/environments
    - Add `DOCKER_HUB_USER` env and set the value to the docker hub account username
    - Add `DOCKER_HUB_PASSWORD` and set the value to a docker hub token for the account (https://docs.docker.com/docker-hub/access-tokens/)
- Re-launch https://github.com/trust-dns/docker/actions/runs/1907593839

**Comment by bluejekyll** [comment]
Ok, I just tried all of that, let's see what happens.

**Comment by bluejekyll** [comment]
btw, we may not want to enable mDNS, I don't have a lot of faith that it's functioning properly.

**Comment by williamdes** [comment]
> btw, we may not want to enable mDNS, I don't have a lot of faith that it's functioning properly.

Oh okay, I can remove it in the next release. Am I missing any other functionality ?

**Comment by williamdes** [comment]
> Ok, I just tried all of that, let's see what happens.

It works, thank you so much !
Ref: https://github.com/trust-dns/docker/runs/5362518557?check_suite_focus=true#step:6:13

**Comment by williamdes** [comment]
Hi @bluejekyll 
Can we add some kind of better aspect and linking to https://hub.docker.com/r/trustdns/trust-dns

It currently looks terrible, maybe in the settings you can link the GitHub repository ?

Let me know and I can provide a README for the homepage, that said you can copy the README.md contents for now

**Comment by williamdes** [comment]
Hi @bluejekyll
Could you please have a look to this thread?

The two main points:
- Add credentials for the CI to be able to push the image itself
- Copy the README to docker hub and connect this repository so users see it's linked. Just do not enable auto builds

**Comment by bluejekyll** [comment]
I've promoted you to admin, btw, on this github repo.

Does that give you enough privileges to update the credentials?

> Copy the README to docker hub and connect this repository so users see it's linked. Just do not enable auto builds

Added.

**Comment by williamdes** [comment]
> > Ok, I just tried all of that, let's see what happens.
> 
> It works, thank you so much ! Ref: https://github.com/trust-dns/docker/runs/5362518557?check_suite_focus=true#step:6:13

Quote one of my previous messages.. 
Sorry for bothering about the token then

I checked and it seems like it was already done: https://github.com/trust-dns/docker/settings/environments/418584772/edit
So we are all good 🎉 
Is it a password or a token that you had put into the variable?

**Comment by williamdes** [comment]
> I've promoted you to admin, btw, on this github repo.

Thank you, that will be easier to maintain this repo

> Added.

Thanks, it looks way better

Maybe I should try building the image multi arch now
