### ISSUE TITLE
Setup integration with docker

### ISSUE THREAD

**Issue by bluejekyll** [hickory-dns/docker#3]
@williamdes, I added a new user to docker,`hickorydns`, I added the `hickory-dns` repository there as well. I added you as a collaborator (I think), can you confirm?

I also performed these actions on this repo:

- Go to the environment "docker-hub" page from the list on https://github.com/hickory-dns/docker/settings/environments
    - Add DOCKER_HUB_USER env and set the value to the docker hub account username
    - Add DOCKER_HUB_PASSWORD and set the value to a docker hub token for the account (https://docs.docker.com/docker-hub/access-tokens/)

**Comment by williamdes** [comment]
> I added you as a collaborator (I think), can you confirm?

Nope, I am not sure why
It's not a big deal since you did the docker push setup, I will try it shortly

**Comment by williamdes** [comment]
Everything works fine
