### ISSUE TITLE
Missing arm image on docker hub

### ISSUE THREAD

**Issue by FourLeafTec** [hickory-dns/docker#4]
With the CI config `PLATFORM: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8`

But there is only `linux/amd64` image on docker hub. 

<img width="689" alt="截屏2023-11-20 16 30 35" src="https://github.com/hickory-dns/docker/assets/5875432/277022df-1798-4364-bc5e-285eb4838a69">

**Comment by williamdes** [comment]
Yeah, I am on it

See: https://github.com/hickory-dns/hickory-dns/issues/2065

I need to apply some fixes and send a build

Thank you for opening this issue !

**Comment by williamdes** [comment]
Done 🎉 
See: https://github.com/hickory-dns/docker/releases/tag/v0.23.0-1
